export type InterestCategory = {
  name: string;
  emoji: string;
  items: string[];
};

// Each item below appears in exactly one category — five concepts (Hiking,
// Nature, Road Trips, Festivals, Fashion) used to be listed under two
// categories at once, which meant getAllInterests() returned duplicate
// entries and the same selectable value showed up twice in the picker UI.
// The chosen canonical category is a judgment call, not a rule; the stored
// value (the plain string) is unchanged either way, so this reshuffle is
// safe for existing users' saved selections.

export const INTEREST_CATEGORIES: InterestCategory[] = [
  {
    name: "Sport",
    emoji: "🏃",
    items: [
      "Gym",
      "Running",
      "Walking",
      "Cycling",
      "Swimming",
      "Soccer",
      "AFL",
      "Rugby",
      "Cricket",
      "Basketball",
      "Tennis",
      "Golf",
      "Volleyball",
      "Martial Arts",
      "Boxing",
      "Yoga",
      "Pilates",
      "Climbing",
      "Fishing",
      "Surfing",
    ],
  },
  {
    name: "Gaming",
    emoji: "🎮",
    items: [
      "PC",
      "PlayStation",
      "Xbox",
      "Nintendo",
      "Retro",
      "RPG",
      "FPS",
      "Strategy",
      "MMOs",
      "Co-op",
      "Esports",
      "Board Games",
      "Card Games",
      "Chess",
      "D&D",
      "Trivia",
      "Escape Rooms",
    ],
  },
  {
    name: "Outdoor",
    emoji: "🌳",
    items: [
      "Hiking",
      "Camping",
      "Beach",
      "Nature",
      "Bushwalking",
      "Kayaking",
      "Stargazing",
      "National Parks",
      "Picnics",
    ],
  },
  {
    name: "Food",
    emoji: "🍕",
    items: [
      "Restaurants",
      "Cafés",
      "Coffee",
      "Brunch",
      "Cooking",
      "Baking",
      "BBQ",
      "Food Markets",
      "Street Food",
      "Fine Dining",
      "Trying New Food",
    ],
  },
  {
    name: "Music",
    emoji: "🎵",
    items: [
      "Concerts",
      "Festivals",
      "Karaoke",
      "Playing Music",
      "Rock",
      "Pop",
      "Hip-Hop",
      "EDM",
      "Metal",
      "Indie",
      "Jazz",
      "Classical",
      "Country",
      "K-Pop",
    ],
  },
  {
    name: "Entertainment",
    emoji: "🎬",
    items: ["Cinema", "Movies", "TV", "Anime", "Manga", "Comedy", "Theatre", "Musicals", "Horror", "Sci-Fi", "Fantasy"],
  },
  {
    name: "Creative",
    emoji: "🎨",
    items: [
      "Photography",
      "Drawing",
      "Painting",
      "Writing",
      "Design",
      "Pottery",
      "DIY",
      "Fashion",
      "Filmmaking",
      "Content Creation",
      "Music Production",
    ],
  },
  {
    name: "Travel",
    emoji: "✈️",
    items: [
      "Travel",
      "Backpacking",
      "Road Trips",
      "Weekend Trips",
      "International Travel",
      "Exploring New Places",
      "Cultural Travel",
    ],
  },
  {
    name: "Learning",
    emoji: "🧠",
    items: [
      "Reading",
      "Book Clubs",
      "History",
      "Science",
      "Technology",
      "AI",
      "Coding",
      "Languages",
      "Psychology",
      "Philosophy",
      "Business",
      "Entrepreneurship",
      "Museums",
    ],
  },
  {
    name: "Animals",
    emoji: "🐕",
    items: ["Dogs", "Cats", "Dog Walking", "Wildlife", "Birdwatching", "Horse Riding"],
  },
  {
    name: "Social",
    emoji: "🤝",
    items: [
      "Meeting New People",
      "Coffee & Chat",
      "Dinner Groups",
      "Casual Hangouts",
      "Parties",
      "Markets",
      "Volunteering",
      "Networking",
      "Community Events",
    ],
  },
  {
    name: "Lifestyle",
    emoji: "😌",
    items: [
      "Wellness",
      "Meditation",
      "Gardening",
      "Mindfulness",
      "Sustainability",
      "Cars",
      "Motorcycles",
      "Drinking",
      "Social Drinking",
      "Smoking",
      "Vaping",
    ],
  },
];

export const ACTIVITIES = [
  "Hiking",
  "Coffee",
  "Restaurants",
  "Gaming",
  "Sports",
  "Gym",
  "Movies",
  "Beach",
  "Road Trips",
  "Concerts",
  "Board Games",
  "Walking",
  "Shopping",
  "Cooking",
  "Photography",
  "Markets",
  "Travel",
  "Nightlife",
  "Yoga",
  "Swimming",
];

export function getAllInterests(): string[] {
  return INTEREST_CATEGORIES.flatMap((cat) => cat.items);
}
